tests:
  "Homepage":
    path: "/"
    assertions:
      - "main.peak_memory < 50MB"
      - "main.wall_time < 100ms"
      - "main.cpu_time < 50ms"
      - "main.network_in < 1MB"
      - "main.network_out < 1MB"
      - "main.peak_memory < 50MB"
      - "main.wall_time < 100ms"
      - "main.cpu_time < 50ms"
      - "main.network_in < 1MB"
      - "main.network_out < 1MB"
