name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, zip
        coverage: none
        
    - name: Install dependencies
      run: |
        composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist
        
    - name: Build assets
      run: |
        npm ci
        npm run build
        
    - name: Deploy to Hostinger via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        port: ${{ secrets.HOSTINGER_PORT }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        script: |
          cd /home/u990109832/public_html
          
          # Create backup
          cp -r . ../backup_$(date +%Y%m%d_%H%M%S)
          
          # Remove old files (keep .htaccess)
          find . -name "*.php" -delete
          find . -name "*.js" -delete
          find . -name "*.css" -delete
          find . -name "*.html" -delete
          rm -rf storage/logs/*.log
          
          # Set permissions
          chmod -R 755 .
          chmod 644 .htaccess
          
    - name: Upload files via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        port: ${{ secrets.HOSTINGER_PORT }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        source: "."
        target: "/home/u990109832/public_html"
        strip_components: 1
        
    - name: Run Laravel commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        port: ${{ secrets.HOSTINGER_PORT }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        script: |
          cd /home/u990109832/public_html
          
          # Set permissions
          chmod -R 755 .
          chmod 644 .htaccess
          chmod -R 775 storage bootstrap/cache
          
          # Run Laravel commands
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan optimize
          
          # Clear old caches
          php artisan cache:clear
          
    - name: Test deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        port: ${{ secrets.HOSTINGER_PORT }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        script: |
          # Test if site is accessible
          curl -f https://coprra.com || exit 1
          
          # Test API endpoint
          curl -f https://coprra.com/api/health || exit 1