name: Performance Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 3 * * 0' # Weekly on Sunday at 3 AM

jobs:
  performance-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: coprra_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, pdo_mysql, curl, zip, bcmath, xdebug
        coverage: xdebug

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Install NPM Dependencies
      run: npm install

    - name: Build Assets
      run: npm run build

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Database Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        DB_DATABASE: coprra_test
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --force

    - name: Seed Database
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        DB_DATABASE: coprra_test
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan db:seed --force

    - name: Run Performance Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        DB_DATABASE: coprra_test
        DB_USERNAME: root
        DB_PASSWORD: root
      run: composer test -- --testsuite=Feature --filter=Performance

    - name: Run Load Tests with Artillery
      run: |
        npm install -g artillery
        php artisan serve --host=0.0.0.0 --port=8000 &
        sleep 10
        artillery quick --count 100 --num 10 http://localhost:8000/api/products

    - name: Generate Performance Report
      run: |
        php artisan test --testsuite=Feature --filter=Performance --coverage-html=coverage/performance
        echo "Performance test results generated in coverage/performance/"

    - name: Upload Performance Results
      uses: actions/upload-artifact@v4
      with:
        name: performance-results
        path: coverage/performance/
